<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 17/12/6
 * Time: 15:01
 */

use think\Lang;

return [
    'changeData' =>[
        'M_Type'           => 'log_M_Type',
        'M_Code'           => 'log_M_Code',
        'P_ID'             => 'log_P_ID',
        'M_Address'        => 'log_M_Address',
        'detail_address'   => 'log_detail_address',
        'U_ID'             => 'log_U_ID',
        'id'               => 'log_id',
        'company_id'       => 'log_company_id',
        'meter_status'     => 'log_meter_status',
        'setup_time'       => 'log_setup_time',
        'username'         => 'log_username',
        'tel'              => 'log_tel',
        'family_num'       => 'log_family_num',
        'building_area'    => 'log_building_area',
        'income_peryear'   => 'log_income_peryear',
        'consumer_state'   => 'log_consumer_state',
        'role_id'          => 'log_role_id',
        'login_name'       => 'log_login_name',
        'status'           => 'log_status',
        'name'             => 'log_name',
        'remark'           => 'log_remark',
        'title'            => 'log_title',
        'pid'              => 'log_pid',
        'rule_val'         => 'log_rule_val',
        'display'          => 'log_display',
        'glyphicon'        => 'log_glyphicon',
        'sortnum'          => 'log_sortnum',
        'type'             => 'log_type',
        'period'           => 'log_period',
        'first_price'      => 'log_first_price',
        'first_val'        => 'log_first_val',
        'second_price'     => 'log_second_price',
        'second_val'       => 'log_second_val',
        'third_price'      => 'log_third_price',
        'third_val'        => 'log_third_val',
        'fourth_price'     => 'log_fourth_price',
        'endtime'          => 'log_endtime',
        'belong'           => 'log_belong',
        'desc'             => 'log_desc',
        'address'          => 'log_address',
        'param_name'       => 'log_param_name',
        'param_type'       => 'log_param_type',
        'opt_id'           => 'log_opt_id',
        'ori_consumer'     => 'log_ori_consumer',
        'new_consumer'     => 'log_new_consumer',
        'old_M_Code'       => 'log_old_M_Code',
        'new_M_Code'       => 'log_new_M_Code',
        'change_reason'    => 'log_change_reason',
        'pulseRatio'       => 'log_pulseRatio',
        'lowLimit'         => 'log_lowLimit',
        'overdraftLimit'   => 'log_overdraftLimit',
        'overdraftTime'    => 'log_overdraftTime',
        'freezeTime'       => 'log_freezeTime',
        'uploadTime'       => 'log_uploadTime',
        'SMSCode'          => 'log_SMSCode',
        'transformerRatio' => 'log_transformerRatio',
        'overFlimit'       => 'log_overFlimit',
        'tag'              => 'log_tag',
        'company_type'     => 'log_company_type',
        'company_name'     => 'log_company_name',
        'quality'          => 'log_quality',
        'contacts_tel'     => 'log_contacts_tel',
        'contacts_name'    => 'log_contacts_name',
        'fax'              => 'log_fax',
        'legal_person'     => 'log_legal_person',
        'bank_name'        => 'log_bank_name',
        'tax_code'         => 'log_tax_code',
        'sms_tel'          => 'log_sms_tel',
        'secret_key_url'   => 'log_secret_key_url',
        'secret_key'       => 'log_secret_key',
        'charge_status'    => 'log_charge_status',
        'charge_date'      => 'log_charge_date',
        'limit_times'      => 'log_limit_times',
        'left_times'       => 'log_left_times',
        'alarm_tel'        => 'log_alarm_tel',
        'OPT_ID'           => 'log_OPT_ID',
        'number'           => 'log_number',
        'reson'            => 'log_reson',
        'code'             => 'log_code',
        'excel_file_path'  => 'log_excel_file_path',
        'ignore_reason'    => 'log_ignore_reason',
        'deal_desc'        => 'log_deal_desc',
        'sdl_preference'   => 'log_sdl_perference',
        'health_auth'      => 'log_health_auth',
        'sdl_auth'         => 'log_sdl_auth',
        'stick'            => 'log_stick',
        'img'              => 'log_img',
        'notify'           => 'log_notify',
        'personName'       => 'log_personName',
        'bank'             => 'log_bank',
        'category'         => 'log_category',
        'sdlprice'         => 'log_sdlprice',
        'rmbprice'         => 'log_rmbprice',
        'sdlenable'        => 'log_sdlenable',
        'rmbenable'        => 'log_rmbenable',
        'freeze'           => 'log_freeze',
        'deli_settle_status' => 'log_deli_settle_status',
        'shop_id'          => 'log_shop_id',
        'value'            => 'log_value',
        'express_company'  => 'log_express_company',
        'express_number'   => 'log_express_number',
    ],

    //定义个人商铺根路径；
    'grImgPath' => 'http://114.113.90.9:10086/',

    //充值类型配置
    'meter_charge_type' => [
        MONEY_CHANNEL_WEIXIN => '微信',
        MONEY_CHANNEL_MANAGE => '系统',
        MONEY_CHANNEL_CARD => '充值卡',
        //MONEY_CHANNEL_BANK => '银行卡',
    ],
];